### ISSUE TITLE
Error with cmake for Chaiscript: 'Can not find Boost'

### ISSUE THREAD

**Issue by bsyzek** [FellowTraveler/Open-Transactions-old#118]
I'm using Ubuntu 12.04 and when following the installation instructions could not configure Chaiscript using cmake. The error I received was 'Can not find Boost'. 

The solution I found was to run 'sudo apt-get install libboost-all-dev' 

It appears that using 'apt-get install libboost-dev' misses something (I'm still not sure what). 

I think that this should be changed in the apt-get (aptitude) part of the instructions.

**Comment by jackson-jackson** [comment]
I had this same error when trying to install on Ubuntu 12.04; the solution you found also worked for me. Now I'm trying to install on OSX and getting the same error but with no clear solution. :(

**Comment by FellowTraveler** [comment]
Looks like this is in the docs/INSTALL instructions now, so I'm closing this old issue.
