### ISSUE TITLE
php

### ISSUE THREAD

**Issue by jspit** [FellowTraveler/Open-Transactions-old#123]
Hi Cameron

I am playing around with otserver

how do you call otserver api from php ?

Can you give me an example of like creating a user / nym using api from php ?

**Comment by jspit** [comment]
HI

Great work on the c++ api.

Managed to write a small php program to test the dll and otapi.php

Call and functions within the classes are ok. 

Note : I noticed that most of the functions within otapi.php are blank.

static function GetTime() {
        return OTAPI_Basic_GetTime();
        }

Is this the way it is meant to be for now or are other files being called ? If so, which lib/dll  files need to be copied to the web folder ?

Thanks

**Comment by jspit** [comment]
the sequence of events for interface is 
from https://github.com/FellowTraveler/Open-Transactions/wiki/API instructions

1) init
2) cleanup
3) setwallet
4) loadwallet  - here it hangs 

shouldn't you connect to the server first using 
OT_API_ConnectServer($SERVER_ID,$USER_ID,$szCA_FILE,$szKEY_FILE,$szKEY_PASSWORD) {

what are the third 3rd and 4th parameters ?

**Comment by jspit** [comment]
great work  on the php class - much better

is there any way to set the path for ot client and server data to be in a one place place only ?

normally they are installed in C:\Users\JSpit-PC\AppData\Roaming\OpenTransactions

but when i run from php another opentransactions folder is created in

to C:\Windows\System32\config\systemprofile\AppData\Roaming

can you also post the lib folder in github so that i can have the latest lib / dll /exe .
when i try to compile the sources i end up with a lot of warnings - most probably due to compatability issues.

**Comment by jspit** [comment]
Cameron

I need your help re point above as I cannot solve it and as such cannot do any web testing

**Comment by FellowTraveler** [comment]
There is now a PHP test script in Open-Transactions/scripts/tests/php

It demonstrates the high-level API through PHP.

Your issue appears to be due to Windows path discrepancies. 

I suggest you open a new issue at github.com/da2ce7/Open-Transactions if necessary, since that is our official Windows build.
