### ISSUE TITLE
getcontract error

### ISSUE THREAD

**Issue by jackson-jackson** [FellowTraveler/Open-Transactions-old#160]
This is on osx mountain lion.

I seem to remember having this problem with previous versions of OT; am I doing something wrong, or is this a bug?

$ opentxs getcontract --args "contract_id rVQaSw2HTXkwEXfqdFJFdisg5Ye1WtFfIvauIiHW4Gx"

Welcome to Open Transactions -- version 0.88.g
User-defined arguments aka:  --args contract_id rVQaSw2HTXkwEXfqdFJFdisg5Ye1WtFfIvauIiHW4Gx

Using as server: rVQaSw2HTXkwEXfqdFJFdisg5Ye1WtFfIvauIiHW4Gx
Using as mynym: O8FfczQiOv5l5PGQorF85h4XeMwYIuLtu5wBIcnTHz1
Using as myacct: TPMqVFKqz3nxRjFwAJuTAEfYmJ4GncyJBQSPGYU2yWt
Using as mypurse: FPIDMisagJo4Heg3vnJYBqDl4LviPBv9arFoeIxh9hs

Usage:  getcontract --server SERVER_ID --mynym YOUR_NYM_ID 
                    --args "contract_id CONTRACT_ID_HERE"

=====>BEGIN Sending getContract message via ZMQ... Request number: 251

=====>BEGIN Sending getRequest message via ZMQ... Request number: 1
Received new request number from the server: 252. Updating Nym records...

=====>BEGIN Sending getContract message via ZMQ... Request number: 252

=====>BEGIN Sending getRequest message via ZMQ... Request number: 1
Received new request number from the server: 253. Updating Nym records...

 ERROR retrieving contract: rVQaSw2HTXkwEXfqdFJFdisg5Ye1WtFfIvauIiHW4Gx

**Comment by FellowTraveler** [comment]
Unreproduceable?
