### ISSUE TITLE
acceptall error

### ISSUE THREAD

**Issue by jackson-jackson** [FellowTraveler/Open-Transactions-old#161]
Whenever I use the 'opentxs acceptall --myacct' command it accepts the transfers but displays this at the end of the output:

Server response (process_inbox): SUCCESS processing/accepting inbox.
Success retrieving intermediary files for account.
BuildFolderPath: Made New Folder: /home/adam/.ot/client_data/paymentInbox/

 accept_from_paymentbox:  OT_API_LoadPaymentInbox Failed.

 accept_from_paymentbox:  OT_API_LoadPaymentInbox Failed.

 accept_from_paymentbox:  OT_API_LoadPaymentInbox Failed.

**Comment by FellowTraveler** [comment]
accept all is a conglomerate command. It performs acceptinbox, acceptpayments, acceptinvoices, accepttransfers, etc.  Therefore this output is proper. You are seeing that the "accept inbox" worked, and the others had empty boxes.
We can fix the output messages to make them less confusing.

I recommend using "showincoming" along with "acceptall" -- they are almost the only two commands you need.
