### ISSUE TITLE
Compilation failed on Linux with G++ 3.8

### ISSUE THREAD

**Issue by ovidiusoft** [FellowTraveler/Open-Transactions-old#192]
Compiling with G++ 3.8 fails with on src/otlib/OTAsymmetricKey.cpp with:

 CXX      libot_la-OTAsymmetricKey.lo
In file included from ../../include/otlib/stacktrace.h:8:0,
                 from OTAsymmetricKey.cpp:165:
/usr/include/c++/4.8.0/cstdlib: In function 'long long int std::abs(long long int)':
/usr/include/c++/4.8.0/cstdlib:174:20: error: declaration of C function 'long long int std::abs(long long int)' conflicts with
   abs(long long __x) { return __builtin_llabs (__x); }
                    ^
/usr/include/c++/4.8.0/cstdlib:166:3: error: previous declaration 'long int std::abs(long int)' here
   abs(long __i) { return __builtin_labs(__i); }
   ^
/usr/include/c++/4.8.0/cstdlib: In function '__int128 std::abs(__int128)':
/usr/include/c++/4.8.0/cstdlib:179:19: error: declaration of C function '__int128 std::abs(__int128)' conflicts with
   abs(__int128 __x) { return __x >= 0 ? __x : -__x; }
                   ^
/usr/include/c++/4.8.0/cstdlib:174:3: error: previous declaration 'long long int std::abs(long long int)' here
   abs(long long __x) { return __builtin_llabs (__x); }
   ^
/usr/include/c++/4.8.0/cstdlib:179:19: error: declaration of C function '__int128 std::abs(__int128)' conflicts with
   abs(__int128 __x) { return __x >= 0 ? __x : -__x; }
                   ^
/usr/include/c++/4.8.0/cstdlib:166:3: error: previous declaration 'long int std::abs(long int)' here
   abs(long __i) { return __builtin_labs(__i); }
   ^
make[1]: **\* [libot_la-OTAsymmetricKey.lo] Error 1

---

The fix is to move #include "stacktrace.h" outside the extern "C":

diff -u OTAsymmetricKey.cpp.bak OTAsymmetricKey.cpp.new  
+++ OTAsymmetricKey.cpp.new 2013-05-17 14:39:50.215610468 +0300
@@ -162,11 +162,13 @@
 #include <unistd.h>
 #endif

-#include "stacktrace.h"
 #include <stdint.h>    

 }

+#include "stacktrace.h"
+
+

**Comment by FellowTraveler** [comment]
Fixed (Thanks!)
