### ISSUE TITLE
zmq Make Error

### ISSUE THREAD

**Issue by lclc** [FellowTraveler/Open-Transactions-old#216]
Hi,

I'm trying to build Open Transactions on openSUSE. I've installed all the necessary dependencies and I've build and installed the newest libzmq (from https://github.com/zeromq/libzmq).
But when building Open Transactions I get errors because there seems to be no zmq::context_t which is used in OpenTransactions.h (http://pastebin.com/vvaSQBwH).

What version of zmq do you use to build OT?
Also I haven't found a commit in zmq which removed context_t from zmq.h..

Edit: I've also tried with libzmq from the repo, same result.

**Comment by skaag** [comment]
I'll try to replicate this on an OpenSuSE VPS

**Comment by lclc** [comment]
Ok thanks.
But I think it doesn't look like a system dependend problem.
OpenTransactions.h uses zmq::context_t (https://github.com/FellowTraveler/Open-Transactions/blob/bb4c3285b6ed8497a42bb58cc5b7f44bb1e0671e/include/otapi/OpenTransactions.h), but that doesn't exist in latest zmq.h include file (https://github.com/zeromq/libzmq/blob/master/include/zmq.h).

Which version of zmq.h / libzmq are you using? Could you upload these files for me?

**Comment by lclc** [comment]
Ahhhh my fault again, sorry.
I was missing the C++ binding for ZMQ..
I'll write the OpenSUSE maintainer to include that file and maybe add a OpenSUSE build doc.

File can be found here: https://github.com/zeromq/cppzmq
