### ISSUE TITLE
should support gnu autoconf for build on mac/unix

### ISSUE THREAD

**Issue by sneak** [FellowTraveler/Open-Transactions-old#25]
most users expect a "./configure --prefix=$blah && make && make install" flow.

**Comment by FellowTraveler** [comment]
I have redone all of the Makefiles to:

1) Auto-detect platform. (Darwin, Linux, FreeBsd, Android.)
2) Simply type "make" from the main folder, or any subfolder, and OT does the rest! (NOTE:  use "make rpc" for preferred XmlRpc mode, from the main folder.)
3) Consolidated (removed) many Makefiles.
4) There are also more options, such as TRANSPORT=XmlRpc, DYNAMIC_OTLIB=1 (necessary on some platforms for the API in some languages.)
5) There is no longer any need to edit any Makefiles, unless your system is non-standard.

So OT doesn't do the ./configure flow exactly as you described (and I encourage others to contribute) but it should be much easier / solved for all practical purposes at this point. 

Improvements also coming to XCode and Windows project files soon...
