### ISSUE TITLE
when I create a voucher with the wallet ... where does it go?

### ISSUE THREAD

**Issue by BlueMeanie** [FellowTraveler/Open-Transactions-old#32]
So I booted up the server and the wallet ... everything seem a-ok.

I create a voucher from the first account for 200.00 .  Where does it go?  How do I put it back in the account?

**Comment by BlueMeanie** [comment]
ok got it to work... tried submitting the same voucher twice and got this:

Received server response to notarize Transactions message.
Loaded transaction 1822, in reference to: 0 type: atDeposit
Loaded transaction Item, transaction num 1822, In Reference To: 1822, type: atDepositCheque, status: rejection
Loaded transaction Item, transaction num 1822, In Reference To: 1822, type: atBalanceStatement, status: rejection

**Comment by FellowTraveler** [comment]
When you withdraw a voucher, the actual voucher is sent to you in the server's reply message. For instructions on how to retrieve the voucher from the reply message, read the Use Cases document under "Withdraw Voucher".  Also see the API document notes for the functions mentioned there.

Once you withdraw 200 from an account, that means the account balance has changed. If your local copy of that account still shows the old balance, then your balance agreements will start to fail (all your future transactions will start failing.) Therefore you might need to call getAccount to download the latest copy of the account. Remember, you must always have the current copy of the account, the inbox, and the outbox, or your balance agreements will fail and the server will thus reject your transactions.

Make sure you also read the Use Cases document on Request Numbers and Transaction Numbers. They are easy but if you don't understand them, your messages and transactions will fail.

Of course: Once you have deposited a voucher, you cannot deposit it twice. So I would also expect it to fail if you continue depositing the same voucher over and over again, when it has already been deposited.

After you deposit the voucher, grab the latest copy of the account and see if the balance has gone back up.

A lot of this stuff is automated in the command-line test client (like re-downloading the account file) but if you are calling the API then you have to do it yourself.

Whenever a message is rejected, look at the output from the Server, and you will see exactly what happened on the server side that caused it to be rejected.

I hope you find this useful.
