### ISSUE TITLE
no make target for 'rpc'

### ISSUE THREAD

**Issue by BlueMeanie** [FellowTraveler/Open-Transactions-old#36]
when I issue

make rpc

it says:

make: **\* No rule to make target `rpc'.  Stop.

**Comment by FellowTraveler** [comment]
Are you in the Open-Transactions folder?

**Comment by BlueMeanie** [comment]
sorry was just about to remove this issue, got it solved.  

Im currently trying to get JNI working...

**Comment by FellowTraveler** [comment]
cd Open-Transactions
make java
cd testwallet

From here, use the otapi.java file.
For an example of how to do it, see my last github message to you with the runme.java example code.
