### ISSUE TITLE
make java    on Ubuntu

### ISSUE THREAD

**Issue by BlueMeanie** [FellowTraveler/Open-Transactions-old#37]
having trouble with

make java

on Ubuntu 10.x

I think you've got it set up to use the open source JDK rather than the Sun JDK.  It is highly preferable to use the Sun JDK.  I don't know how the open source JDK might behave and most likely finding out is going to be costly and tedious exercise.  Where do you set the -I option for gcc in the Makefile?  can I edit that?

**Comment by FellowTraveler** [comment]
Make any edits you feel necessary and pls send me notes.
You have a fork, right? I can just compare the two forks later.

**Comment by FellowTraveler** [comment]
Look in testwallet/Makefile.API

The line:
JAVA_INCLUDEDIRS = -I/usr/$(LINUX_LIBDIR)/jvm/java-6-openjdk/include

**Comment by BlueMeanie** [comment]
thanks.

**Comment by BlueMeanie** [comment]
yep thats the problem, you're more or less specifying to use the OSS java jdk.  Not really a good idea... these problems can get pretty extensive and I need to think of a strategy to manage them.  The Open JDK is not really stable IMHO.

**Comment by FellowTraveler** [comment]
If you have:
1) A specific command line command for installing the sun version for linux.
...Then I will add it to the instructions.
2) A correction for Makefile.API 
...Then I will update the makefile as well.

Let me know how it goes, I'm not married to any specific java implementation.

**Comment by BlueMeanie** [comment]
how do I add a compiler option to the Makefile.API?
