### ISSUE TITLE
SECURITY: need separate keys for signing and encryption

### ISSUE THREAD

**Issue by FellowTraveler** [FellowTraveler/Open-Transactions-old#39]
Nyms need to have 2 key pairs: one for signing and one for encryption.

**Comment by BlueMeanie** [comment]
why do you need separate keys?

**Comment by FellowTraveler** [comment]
It's a recommended "good practice" in crypto to use different keys for signing and encryption. I think even your PGP key does this. Perhaps OT already does it internally by way of OpenSSL -- I need to research that and if not, add another key to OTPseudonym.

**Comment by FellowTraveler** [comment]
With the new credentials system, OT now has 3 key pairs for each credential: signing, authentication, and encryption. Each Nym can have multiple master credentials, and each of those can issue multiple subcredentials.
