### ISSUE TITLE
Get user feedback: Lua in contracts...

### ISSUE THREAD

**Issue by FellowTraveler** [FellowTraveler/Open-Transactions-old#47]
I realized that Lua code can be added inside the contracts, based on a standard interface, with access to certain standard objects (read-only or whatever). When those parts of the contracts are activated, the appropriate data objects can be passed into the Lua code. Certainly custom rules can be added to contracts by this mechanism (especially those that return true/false.) There is a whole level of business intelligence that can be added at this layer, without changing any of the code inside OT itself.

I need to get user feedback on how they would use this feature, so that I can define the interface clearly. (So that Lua functions implementing that standard interface can be added to the contracts.)

**Comment by rlindsay** [comment]
My initial thoughts are, if you have a spec, this would be listed as an optional part of the spec. Or an 'extension' to it. My reasoning is that it doesn't sound like a critical aspect of OT contracts. I may be wrong on this. Also, if you add in too much complexity before the project has much takeup you might be limiting takeup incentive (that is, if every part of the spec is listed as a MUST implement).

_edit_ Smart Contracts?
http://en.wikipedia.org/wiki/Smart_contract
http://www.erights.org/smart-contracts/index.html

**Comment by FellowTraveler** [comment]
Also check out Chai Script and Angel Script.

**Comment by FellowTraveler** [comment]
Closing this issue, as OT is now fully-scriptable on the client side as well as in smart contracts.
