### ISSUE TITLE
Use solid computer readable formats for all data storage.

### ISSUE THREAD

**Issue by da2ce7** [FellowTraveler/Open-Transactions-old#66]
Clearsign should be only used for when a asset is being view by a human... In all storage, (where the computer reads the asset), it should be either stored in an text-armored or binary format.

This issue has arisen from the many-issues caused by line ending and changing spaces to tabs and other visual-only changes happening to assets saved in clear-sign formats the cryptographic signature is destroyed by such trivial changes.

For development purposes it may be wise to keep a human readable copy of the asset in the header of the asset. However it must be prefaced with some text like:

!!! IMPORTANT !!!!
This plain text of the contract is for development information purposes only!!!
Please load this contract up in openssl for verification and certified output.

**Comment by FellowTraveler** [comment]
This is done -- all text files are now stored in "OT Armored" format.

(All binary files, of which there are few, are stored in protobuf.)
